name: hop
version: 0.26.0-dev
author: Kevin Moore <kevin@thinkpixellab.com>
description: Dart Task Framework
homepage: https://github.com/kevmoo/hop.dart
documentation: http://kevmoo.github.io/hop.dart
environment:
  sdk: '>=0.8.1'
dependencies:
  args: '>=0.8.1'
  bot: '>=0.23.1'
  bot_io: '>=0.23.2'
  html5lib: '>=0.8.1'
  logging: '>=0.8.1'
  meta: '>=0.8.1'
  path: '>=0.8.1'
  unittest: '>=0.8.1'
dev_dependencies:
  bot_test: '>=0.1.2'
