name: hop
version: 0.23.0
author: Kevin Moore <kevin@thinkpixellab.com>
description: Dart Task Framework
homepage: https://github.com/kevmoo/hop.dart
documentation: http://kevmoo.github.io/hop.dart
environment:
  sdk: '>=0.6.3+3'
dependencies:
  args: '>=0.6.3'
  bot: '>=0.22.1'
  bot_io: '>=0.21.2'
  logging: '>=0.6.3'
  meta: '>=0.6.3'
  pathos: '>=0.6.3'
  unittest: '>=0.6.3'
dev_dependencies:
  html5lib: '>=0.4.3'
