name: hop
version: 0.30.5-dev
author: Hop Project Authors
description: Dart Task Framework
homepage: https://github.com/dart-lang/hop
environment:
  sdk: '>=1.4.0 <2.0.0'
documentation: http://dart-lang.github.io/hop/
dependencies:
  args: '>=0.9.0 <0.12.0'
  bot: '>=0.26.0 <0.28.0'
  bot_io: '>=0.26.1 <0.27.0'
  collection: '>=0.9.0 <0.10.0'
  completion: '>=0.1.0 <0.2.0'
  hop_git: '>=0.1.0 <0.2.0'
  hop_unittest: '>=0.1.0 <0.2.0'
  logging: '>=0.9.1 <0.10.0'
  path: '>=0.9.0 <2.0.0'
dev_dependencies:
  git: '>=0.1.0 <0.5.0'
  hop_docgen: '>=0.1.0 <0.2.0'
  unittest: '>=0.9.0 <0.12.0'
