name: hop
version: 0.24.3
author: Kevin Moore <kevin@thinkpixellab.com>
description: Dart Task Framework
homepage: https://github.com/kevmoo/hop.dart
documentation: http://kevmoo.github.io/hop.dart
environment:
  sdk: '>=0.6.20'
dependencies:
  args: '>=0.6.17'
  bot: '>=0.23.0'
  bot_io: '>=0.23.1'
  html5lib: '>=0.6.20'
  logging: '>=0.6.20'
  meta: '>=0.6.20'
  path: '>=0.6.20'
  unittest: '>=0.6.20'
dev_dependencies:
  bot_test: '>=0.1.2'
