name: hop
version: 0.28.0-dev
author: Kevin Moore <kevin@thinkpixellab.com>
description: Dart Task Framework
homepage: https://github.com/kevmoo/hop.dart
documentation: http://kevmoo.github.io/hop.dart
environment:
  sdk: '>=0.8.10+4'
dependencies:
  args: '>=0.8.10+4'
  bot: '>=0.24.0'
  bot_io: '>=0.24.0'
  html5lib: '>=0.8.10+4'
  logging: '>=0.8.10+4'
  path: '>=0.8.10+4'
  unittest: '>=0.8.10+4'
  unmodifiable_collection: '>=0.8.10+4'
dev_dependencies:
  bot_test: '>=0.1.3'
