name: hop
version: 0.24.3+2
author: Kevin Moore <kevin@thinkpixellab.com>
description: Dart Task Framework
homepage: https://github.com/kevmoo/hop.dart
documentation: http://kevmoo.github.io/hop.dart
environment:
  sdk: '>=0.6.21+3'
dependencies:
  args: '>=0.6.21+3'
  bot: '>=0.23.0'
  bot_io: '>=0.23.2'
  html5lib: '>=0.6.21+3'
  logging: '>=0.6.21+3'
  meta: '>=0.6.21+3'
  path: '>=0.6.21+3'
  unittest: '>=0.6.21+3'
dev_dependencies:
  bot_test: '>=0.1.2'
