name: hop
version: 0.23.0-dev
author: Kevin Moore <kevin@thinkpixellab.com>
description: Dart Task Framework
homepage: https://github.com/kevmoo/hop.dart
documentation: http://kevmoo.github.io/hop.dart
environment:
  sdk: '>=0.5.16'
dependencies:
  args: '>=0.5.16'
  bot: '>=0.21.0'
  bot_io: '>=0.21.2'
  logging: '>=0.5.16'
  meta: '>=0.5.16'
  pathos: '>=0.5.16'
  unittest: '>=0.5.16'
dev_dependencies:
  html5lib: '>=0.4.3'
