name: hop
version: 0.26.0-dev
author: Kevin Moore <kevin@thinkpixellab.com>
description: Dart Task Framework
homepage: https://github.com/kevmoo/hop.dart
documentation: http://kevmoo.github.io/hop.dart
environment:
  sdk: '>=0.8.5'
dependencies:
  args: '>=0.8.5'
  bot: '>=0.24.0'
  bot_io: '>=0.23.2'
  html5lib: '>=0.8.5'
  logging: '>=0.8.5'
  meta: '>=0.8.5'
  path: '>=0.8.5'
  unittest: '>=0.8.5'
dev_dependencies:
  bot_test: '>=0.1.2'
