name: hop
version: 0.26.1-dev
author: Kevin Moore <kevin@thinkpixellab.com>
description: Dart Task Framework
homepage: https://github.com/kevmoo/hop.dart
documentation: http://kevmoo.github.io/hop.dart
environment:
  sdk: '>=0.8.8'
dependencies:
  args: '>=0.8.8'
  bot: '>=0.24.0'
  bot_io: '>=0.23.3'
  html5lib: '>=0.8.8'
  logging: '>=0.8.8'
  path: '>=0.8.8'
  unittest: '>=0.8.8'
dev_dependencies:
  bot_test: '>=0.1.3'
