name: hop
author: Kevin Moore <kevin@thinkpixellab.com>
version: 0.28.2+1
homepage: https://github.com/kevmoo/hop.dart
environment:
  sdk: '>=1.0.0 <2.0.0'
description: Dart Task Framework
documentation: http://kevmoo.github.io/hop.dart
dependencies:
  args: '>=0.9.0 <0.11.0'
  bot: '>=0.26.0'
  bot_io: '>=0.25.1+1'
  collection: '>=0.9.0 <0.10.0'
  html5lib: '>=0.9.1 <0.10.0'
  logging: '>=0.9.1 <0.10.0'
  path: '>=0.9.0 <2.0.0'
  unittest: '>=0.9.0 <0.10.0'
dev_dependencies:
  bot_test: '>=0.1.5'
