name: hop
version: 0.24.1-dev
author: Kevin Moore <kevin@thinkpixellab.com>
description: Dart Task Framework
homepage: https://github.com/kevmoo/hop.dart
documentation: http://kevmoo.github.io/hop.dart
environment:
  sdk: '>=0.6.9'
dependencies:
  args: '>=0.6.9'
  bot: '>=0.22.2'
  bot_io: '>=0.22.0+2'
  logging: '>=0.6.9'
  meta: '>=0.6.9'
  path: '>=0.6.9'
  unittest: '>=0.6.9'
dev_dependencies:
  bot_test:
    git: https://github.com/kevmoo/bot_test.dart.git
  html5lib: '>=0.4.3'
