name: hop
author: Kevin Moore <kevin@thinkpixellab.com>
version: 0.28.0-dev
homepage: https://github.com/kevmoo/hop.dart
sdk:
  sdk: '>=0.8.10+6 <2.0.0'
description: Dart Task Framework
documentation: http://kevmoo.github.io/hop.dart
environment:
  sdk: '>=0.8.10+6 <2.0.0'
dependencies:
  args: '>=0.9.0 <0.10.0'
  bot: '>=0.24.0'
  bot_io: '>=0.24.0'
  collection_helpers: any
  html5lib: '>=0.9.0 <0.10.0'
  logging: '>=0.9.0 <0.10.0'
  path: '>=0.9.0 <0.10.0'
  unittest: '>=0.9.0 <0.10.0'
  unmodifiable_collection: '>=0.9.0 <0.10.0'
dev_dependencies:
  bot_test: '>=0.1.5'
