name: hop
version: 0.31.2-dev
author: Hop Project Authors <hop_authors@j832.com>
description: Dart Task Framework
homepage: https://github.com/kevmoo/hop
environment:
  sdk: '>=1.9.0 <2.0.0'
dependencies:
  args: '>=0.9.0 <0.14.0'
  bot: '>=0.26.0 <0.29.0'
  bot_io: ^0.26.1
  collection: ^1.0.0
  completion: ^0.1.4
  logging: ^0.9.1
  path: ^1.0.0
dev_dependencies:
  hop_unittest: ^0.1.0
  unittest: ^0.11.0
executables:
  bench:
