name: hop
version: 0.24.2-dev
author: Kevin Moore <kevin@thinkpixellab.com>
description: Dart Task Framework
homepage: https://github.com/kevmoo/hop.dart
documentation: http://kevmoo.github.io/hop.dart
environment:
  sdk: '>=0.6.9'
dependencies:
  args: '>=0.6.9'
  bot: '>=0.23.0'
  bot_io: '>=0.23.0'
  logging: '>=0.6.9'
  meta: '>=0.6.9'
  path: '>=0.6.9'
  unittest: '>=0.6.9'
dev_dependencies:
  bot_test: '>=0.1.1'
  html5lib: '>=0.4.4'
